from .spider_interface import CONST

# ============================================================
# Scrapy settings for kijiji_spider
# All values come from spider_interface.py CONST
# ============================================================

BOT_NAME = CONST["BOT_NAME"]

SPIDER_MODULES = ["kijiji_spider.spiders"]
NEWSPIDER_MODULE = "kijiji_spider.spiders"

ADDONS = {}

USER_AGENT = CONST["USER_AGENT"]
ROBOTSTXT_OBEY = CONST["ROBOTSTXT_OBEY"]

CONCURRENT_REQUESTS_PER_DOMAIN = CONST["CONCURRENT_REQUESTS_PER_DOMAIN"]
DOWNLOAD_DELAY = CONST["DOWNLOAD_DELAY"]
RANDOMIZE_DOWNLOAD_DELAY = CONST["RANDOMIZE_DOWNLOAD_DELAY"]
COOKIES_ENABLED = CONST["COOKIES_ENABLED"]

RETRY_TIMES = CONST["RETRY_TIMES"]
RETRY_HTTP_CODES = CONST["RETRY_HTTP_CODES"]
DEFAULT_REQUEST_HEADERS = CONST["DEFAULT_REQUEST_HEADERS"]

AUTOTHROTTLE_ENABLED = CONST["AUTOTHROTTLE_ENABLED"]
AUTOTHROTTLE_START_DELAY = CONST["AUTOTHROTTLE_START_DELAY"]
AUTOTHROTTLE_MAX_DELAY = CONST["AUTOTHROTTLE_MAX_DELAY"]
AUTOTHROTTLE_TARGET_CONCURRENCY = CONST["AUTOTHROTTLE_TARGET_CONCURRENCY"]

HTTPCACHE_ENABLED = CONST["HTTPCACHE_ENABLED"]
HTTPCACHE_EXPIRATION_SECS = CONST["HTTPCACHE_EXPIRATION_SECS"]
HTTPCACHE_DIR = CONST["HTTPCACHE_DIR"]
HTTPCACHE_IGNORE_HTTP_CODES = CONST["HTTPCACHE_IGNORE_HTTP_CODES"]
HTTPCACHE_STORAGE = CONST["HTTPCACHE_STORAGE"]

ITEM_PIPELINES = {
    "kijiji_spider.pipelines.KijijiSpiderPipeline": 300,
}

DOWNLOADER_MIDDLEWARES = {
    "kijiji_spider.middlewares.UserAgentRotationMiddleware": 400,
    "kijiji_spider.middlewares.KijijiSpiderDownloaderMiddleware": 543,
}

FEED_EXPORT_ENCODING = CONST["FEED_EXPORT_ENCODING"]
LOG_LEVEL = CONST["LOG_LEVEL"]
