
services:
  backend:
    build:
      context: .
      dockerfile: Modules/user_GUI/back_end/Dockerfile
    container_name: backend-app
    ports:
      - "8000:8000"
    volumes:
      - ./user_GUI/back_end:/app

  frontend:
    build:
      context: .
      dockerfile: Modules/user_GUI/front_end/Dockerfile
    container_name: frontend-app
    ports:
      - "5173:5173"
    volumes:
      - ./Modules/user_GUI/front_end:/app
      - /app/node_modules
    depends_on:
      - backend