version: '3.8'
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama # save ollama data in a named volume
  app:
    build: .
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434 # make app connect to ollama service
    volumes:
      - ./__ingest_file:/app/__ingest_file
      - ./__processed_file:/app/__processed_file
  backend:
    build: .
    command: uvicorn Modules.user_GUI.back_end.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - ollama
volumes:
  ollama_data:
