"""
Spider Standard Object

This is the default object all spiders should use to store listing data.
All spider objects should be mapped into this class before saving to the central DB.

Updated by: Yung (Philip)
- Fixed __init__ parameter list to match all self.xxx fields
- Added default values for optional fields
- Added to_dict() for DB/CSV storage
"""

import sqlite3
from pathlib import Path
import hashlib
from bs4 import BeautifulSoup
import ollama
from datetime import datetime
from typing import Optional
import json
from typing import Optional

#======= Custom libs 
from .spider_std_obj_interface import CONST


class Post_Data():
     
     #== Obj variables
     post_description_obj=None #-- obj with LLM parsed data 
     db_path=None

     def __init__(self, 
               post_id,time_of_post, user_post_title, user_meta_tags, post_url, price_of_the_unit, sqr_feet_lot, general_area, street_number, city, province, postal_code, bed,bath, square_feet_unit, post_description, rent_period, leasing_agent, first_img_url
          ):
   
          self.post_id=post_id
          self.time_of_post=time_of_post
          self.user_post_title=user_post_title
          self.user_meta_tags=user_meta_tags
          self.post_url=post_url
          self.price_of_the_unit=price_of_the_unit
          self.sqr_feet_lot=sqr_feet_lot
          self.general_area=general_area
          self.street_number=street_number
          self.city=city
          self.province=province
          self.postal_code=postal_code
          self.bed=bed
          self.bath=bath
          self.square_feet_unit=square_feet_unit
          self.post_description=post_description
          self.rent_period=rent_period
          self.leasing_agent=leasing_agent
          self.first_img_url=first_img_url

          if self.post_description not in [None, "N/A", "","None"]:
               self.parse_description()
         
     def parse_description(self):
          if self.post_description != None:
               post_dec=self.Post_Description_Parser()
               post_dec.ingest_post_description(self.post_description)
               self.post_description_obj= post_dec
     
     def __create_db(self):
          base=Path(__file__).resolve().parent
          self.db_path = f"{base}/{CONST['DB_LOCATION']}/{CONST['DB_NAME']}"

          #== connect to db 
          conn = sqlite3.connect(self. db_path)
          cursor = conn.cursor()
          cursor.execute(CONST["FORIGHN_KEYS_ON"]) #TURN ON FORIGHN KEYS 
          
          #== create tables 
          cursor.execute(CONST["CREATE_TABLE_LISTINGS"]) 
          cursor.execute(CONST["CREATE_TABLE_POST_DESCRIPTION"])  
          cursor.execute(CONST["CREATE_TABLE_POST_STATUS"]) 
          conn.commit()   # ← save changes

     def __conn_to_db(self):
          self.__create_db()
          with sqlite3.connect(self.db_path) as conn:
               cursor = conn.cursor()
               return cursor,conn

     def save_new_post_to_db(self):
          # try:
          cursor, conn = self.__conn_to_db()        

          #== insert the post 
          cursor.execute(CONST["INSERT_LISTING"], (
               self.post_id,
               self.post_url,
               self.time_of_post,
               self.leasing_agent,
               self.general_area,
               self.street_number,
               self.city,
               self.province,
               self.postal_code,
               self.price_of_the_unit,
               self.square_feet_unit,
               self.bed,
               self.bath,
               self.rent_period,
               self.user_post_title,
               self.first_img_url,        
               self.user_meta_tags,
               self.post_description,
               self.first_img_url,
               ))#scraped at is auto generated by the database, created at time of inserting record. 

          listing_id=cursor.lastrowid #this is the ID if the insert_post - going to be FK for other tables

          if self.post_description_obj != None: #None if the model fails to parse content
               #== insert post's meta data from parsing it with LLM
               cursor.execute(CONST["INSERT_PARSED_POST_DESCRIPTION"], (
                    listing_id, #this is the forign key which is based on previous insert
                    self.post_description_obj.smoke_free ,
                    self.post_description_obj.private_room ,
                    self.post_description_obj.living_situation ,
                    self.post_description_obj.wheelchair_accessible ,
                    self.post_description_obj.has_ac ,
                    self.post_description_obj.w_d_in_unit ,
                    self.post_description_obj.furnished ,
                    self.post_description_obj.luxuries ,
                    self.post_description_obj.sq_footage ,
                    self.post_description_obj.price_per_month ,
                    self.post_description_obj.included_utilities ,
                    self.post_description_obj.utility_cap ,
                    self.post_description_obj.close_to ,
                    self.post_description_obj.travel_convenience ,
                    self.post_description_obj.pets_okay ,
                    self.post_description_obj.cats_okay ,
                    self.post_description_obj.dogs_okay ,
                    self.post_description_obj.parking_included ,
                    self.post_description_obj.parking_spots ,
                    self.post_description_obj.parking_ev_charging ,
                    self.post_description_obj.parking_details ,
                    self.post_description_obj.damage_deposit ,
                    self.post_description_obj.other_deposits ,
                    self.post_description_obj.req_references ,
                    self.post_description_obj.req_credit_check ,
                    self.post_description_obj.req_criminal_record_check ,
                    self.post_description_obj.req_other ,
                    self.post_description_obj.llm_model_comments ,
                    ))

          conn.commit()

          print("\n\n=========Spider Saved Post and Post Description to DB Successfully=======")
          print(f"row ID: {listing_id}\n\n")


          # except Exception as e:
          #      print(CONST["ERR_MSG_1"])
          #      print(f"DEV: MUTE BEFORE DEPLOY: \n\n {e} \n\n")

     def get_record_by_url(self, url) -> Optional[list]:
          #this method checks if the post exists in db based on it's url. 
          sql_query = CONST["SQL_GET_ROW_BY_URL"] 

          cursor,conn=self.__conn_to_db()
          cursor.execute(sql_query, (url,))
          data= cursor.fetchone() #single row 
          conn.close()

          return data #[1, "address"]

     def update_post_last_active(self,scraped_at,active_post=bool,row_id=int ):
          cursor,conn=self.__conn_to_db()

          #determin time on market based off scraped at:  2026-06-28 02:19:09
          days_on_market=self.__get_days_on_market(scraped_at)
          cursor.execute(CONST["INSERT_POST_STATUS"],(active_post, days_on_market,row_id)) #post status, time_on_market, listing_id

          conn.close()


     def __get_current_time(self):
          return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
     
     def __get_days_on_market(self, scraped_at_previously):
          # parse the stored date string back to datetime
          posted_date = datetime.strptime(f"{scraped_at_previously}", "%Y-%m-%d %H:%M:%S")

          # subtract from today
          days_on_market = (datetime.now() - posted_date).days

          return days_on_market  # 0, 5, 30 etc

     def DEV_drop_table_manual(self,):
          #making it namual so you'll have do it intentially.

          cursor,conn=self.__conn_to_db()

          cursor.execute("DROP TABLE IF EXISTS post_status")
          conn.commit()  # ← must have this


     class Post_Description_Parser:

          def __init__(self):
               # Basic Info
               self.smoke_free: Optional[bool] = None
               self.private_room: Optional[bool] = None
               self.living_situation: Optional[str] = None
               self.has_ac: Optional[bool] = None
               self.w_d_in_unit: Optional[bool] = None
               self.furnished: Optional[bool] = None
               self.wheelchair_accessible: Optional[bool] = None
               self.sq_footage: Optional[int] = None
               self.price_per_month: Optional[int] = None
               self.included_utilities: Optional[str] = None
               self.utility_cap: Optional[str] = None
               self.close_to: Optional[str] = None
               self.travel_convenience: Optional[str] = None
               self.luxuries: Optional[str] = None
               self.llm_model_comments: Optional[str] = None

               # Pet Policy
               self.pets_okay: Optional[bool] = None
               self.cats_okay: Optional[bool] = None
               self.dogs_okay: Optional[bool] = None

               # Parking
               self.parking_included: Optional[bool] = None
               self.parking_spots: Optional[int] = None
               self.parking_ev_charging: Optional[bool] = None
               self.parking_details: Optional[str] = None

               # Deposit
               self.damage_deposit: Optional[str] = None
               self.other_deposits: Optional[str] = None

               # Requirements
               self.req_credit_check: Optional[bool] = None
               self.req_references: Optional[bool] = None
               self.req_criminal_record_check: Optional[bool] = None
               self.req_other: Optional[str] = None
          
          def parse_llm_response(self, response):
               data = None
               try:
                    # handle both string and dict responses
                    if isinstance(response, str):
                         clean = response.replace("```json", "").replace("```", "").strip()
                         data = json.loads(clean)
                    else:
                         data = response

               except Exception as e:
                    self.llm_parsed_successfully = False
                    print(f"==== LLM FAILED TO PARSE: {e} ====")
                    return None

               self.llm_parsed_successfully = True

               # basic info
               self.smoke_free                 = data.get("smoke_free")
               self.private_room               = data.get("private_room")
               self.living_situation           = data.get("living_situation")
               self.available_from             = data.get("available_from")
               self.property_type              = data.get("property_type")
               self.has_ac                     = data.get("has_ac")
               self.w_d_in_unit                = data.get("w_d_in_unit")
               self.furnished                  = data.get("furnished")
               self.wheelchair_accessible      = data.get("wheelchair_accessible")
               self.sq_footage                 = data.get("sq_footage")
               self.price_per_month            = data.get("price_per_month")
               self.included_utilities         = data.get("included_utilities")
               self.utility_cap                = data.get("utility_cap")
               self.close_to                   = data.get("close_to")
               self.travel_convenience         = data.get("travel_convenience")
               self.luxuries                   = data.get("luxuries")
               # pets
               self.pets_okay                  = data.get("pets_okay")
               self.cats_okay                  = data.get("cats_okay")
               self.dogs_okay                  = data.get("dogs_okay")
               # parking
               self.parking_included           = data.get("parking_included")
               self.parking_spots              = data.get("parking_spots")
               self.parking_ev_charging        = data.get("parking_ev_charging")
               self.parking_details            = data.get("parking_details")
               # deposits
               self.damage_deposit             = data.get("damage_deposit")
               self.other_deposits             = data.get("other_deposits")
               # requirements
               self.req_credit_check           = data.get("req_credit_check")
               self.req_references             = data.get("req_references")
               self.req_criminal_record_check  = data.get("req_criminal_record_check")
               self.req_other                  = data.get("req_other")
               # comments
               self.llm_model_comments         = data.get("llm_model_comments")

               return self

          def ingest_post_description(self, document):       #private method
               #ref: https://github.com/ollama/ollama-python
               crashes=0
               response=""
               while crashes<CONST["LLM_CRASH_LIMIT"]:
                    # try:
                    print("\n====== Parsing Description Using LLM ===========\n") 
                    print(f"The description: \n{document}")
                    print("\n\n")
                    instruction= f"{CONST["LLM_OUTPUT_OBJ_INSTRUCTIONS"]} Document:{document}"
                    
                    response=ollama.chat(
                         model=CONST["MODEL_NAME"],          
                         messages=[
                              {"role": "system","content": CONST["SYSTEM_ROLE"]},
                              {"role": "user","content":instruction}],
                              stream= True
                         )
                    full_response = ""
                    for chunk in response:
                         token = chunk['message']['content']
                         # print(token, end='', flush=True)
                         full_response += token

                    self.parse_llm_response(full_response)
                    return full_response

               # except Exception as e:
               #      crashes+=1
               #      print(f"Ollama call:  {e}"  )
               #      print("Model Crashed")               

          # return response #return empty string if the model keeps crashing.
     




# we can fall back on this one if needed. 
# class SpiderData_Default_Obj(): #clean input before putting into this obj
#     def __init__(self,
#         # Required fields
#         title,
#         listing_url,
#         source_website,
#         first_seen,
#         last_seen,
#         status,
#         address,
#         street_address,
#         neighbourhood,
#         city,
#         province,
#         price,
#         bedrooms,
#         bathrooms,
#         square_feet,
#         lot_size,
#         property_type,
#         features,
#         facilities,
#         agent_name,
#         brokerage,

#         # Optional fields (default N/A)
#         img_of_unit="N/A",
#         days_ago_posted="N/A",
#         post_updated="N/A",
#         post_description="N/A",
#         move_in_date="N/A",
#         security_deposit="N/A",
#         min_rental_period="N/A",
#         amenities="N/A",       # fixed typo: amenties → amenities
#         pet="N/A",
#         appliances="N/A",      # laundry, stove, dishwasher, washer, dryer
#         parking="N/A",
#         locker="N/A",
#         smoking="N/A",
#     ):
#         # == Meta: about the post
#         self.title = title
#         self.listing_url = listing_url
#         self.source_website = source_website
#         self.img_of_unit = img_of_unit

#         # == Market speed
#         self.days_ago_posted = days_ago_posted
#         self.post_updated = post_updated
#         self.first_seen = first_seen
#         self.last_seen = last_seen
#         self.status = status

#         # == Address of the home
#         self.address = address
#         self.street_address = street_address
#         self.neighbourhood = neighbourhood
#         self.city = city
#         self.province = province

#         # == About the unit
#         self.price = price
#         self.bedrooms = bedrooms
#         self.bathrooms = bathrooms
#         self.square_feet = square_feet
#         self.lot_size = lot_size
#         self.property_type = property_type
#         self.post_description = post_description
#         self.move_in_date = move_in_date
#         self.security_deposit = security_deposit
#         self.min_rental_period = min_rental_period

#         # == Features
#         self.amenities = amenities      # fixed typo: amenties → amenities
#         self.features = features
#         self.facilities = facilities
#         self.pet = pet
#         self.appliances = appliances    # laundry, stove, dishwasher, washer, dryer
#         self.parking = parking
#         self.locker = locker
#         self.smoking = smoking

#         # == Seller info
#         self.agent_name = agent_name
#         self.brokerage = brokerage

#     def get_hash(self) -> str:
#         """Generate unique hash from listing URL."""
#         return hashlib.md5(self.listing_url.encode()).hexdigest()

#     def to_dict(self) -> dict:
#         """Convert to dictionary for DB/CSV storage."""
#         return {
#             "listing_hash": self.get_hash(),
#             "title": self.title,
#             "listing_url": self.listing_url,
#             "source_website": self.source_website,
#             "img_of_unit": self.img_of_unit,
#             "days_ago_posted": self.days_ago_posted,
#             "post_updated": self.post_updated,
#             "first_seen": self.first_seen,
#             "last_seen": self.last_seen,
#             "status": self.status,
#             "address": self.address,
#             "street_address": self.street_address,
#             "neighbourhood": self.neighbourhood,
#             "city": self.city,
#             "province": self.province,
#             "price": self.price,
#             "bedrooms": self.bedrooms,
#             "bathrooms": self.bathrooms,
#             "square_feet": self.square_feet,
#             "lot_size": self.lot_size,
#             "property_type": self.property_type,
#             "post_description": self.post_description,
#             "move_in_date": self.move_in_date,
#             "security_deposit": self.security_deposit,
#             "min_rental_period": self.min_rental_period,
#             "amenities": self.amenities,
#             "features": self.features,
#             "facilities": self.facilities,
#             "pet": self.pet,
#             "appliances": self.appliances,
#             "parking": self.parking,
#             "locker": self.locker,
#             "smoking": self.smoking,
#             "agent_name": self.agent_name,
#             "brokerage": self.brokerage,
#         }
